# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala

scala:
   - 2.10.5
   - 2.11.7

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7

notifications:
  email:
    recipients:
      - tim@coding-me.com

script: sbt ++$TRAVIS_SCALA_VERSION test
