# See http://about.travis-ci.org/docs/user/build-configuration/
sudo: false

language: scala

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

# Fix https://github.com/travis-ci/travis-ci/issues/4527
before_script:
  - mkdir -p $HOME/.sbt/launchers/0.13.8/
  - curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar

scala:
  - 2.11.7

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email:
    recipients:
      - tim@coding-me.com

script:
  - sbt clean coverage test
# Don't aggregate now, only one subproject: - sbt coverageAggregate


after_success:
  - sbt coveralls
